Invoices visual fix
peterprospl12/PotterShop pull request #67
Opened 2024-12-11 16:33 UTC by peterprospl12

2024-12-24 20:18 UTC, tomaszsankowski requested changes
Przecież ty shardkodowałeś adres sklepu lol

2024-12-26 16:09 UTC, peterprospl12 commented
> Przecież ty shardkodowałeś adres sklepu lol

recenzent dal approved xd

2024-12-29 13:24 UTC, tomaszsankowski commented
nie akceptujcie jeszcze

2024-12-29 15:06 UTC, tomaszsankowski commented
Ok dajcie approve

2024-12-29 21:00 UTC, tomaszsankowski approved these changes
good work!

2024-12-29 21:07 UTC, kmonieczny approved these changes
approved

2024-12-29 21:10 UTC, merged